site_name: one-liner
site_description: Remote RPC and streaming utilities over ZeroMQ.
repo_url: https://github.com/AllenNeuralDynamics/one-liner
site_dir: site

docs_dir: docs

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.magiclink # For in-line references to functions/methods.

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            filters:
              - "!^__slots__$" # Omit slots
            show_root_heading: true
            show_if_no_docstring: false
            show_source: false
            members_order: source
            docstring_style: numpy

nav:
  - Home: index.md
  - API:
      - Client: api/client.md
      - Server: api/server.md
